version: '3'
services:
  react:
    build:
      context: ./
    ports:
      - "3000:3000"
    container_name: react-meu-time
    stdin_open: true
    volumes:
       - .:/usr/src/app/meu-time-react-app
       - /usr/src/app/meu-time-react-app/node_modules